-- Align existing MLM levels with the published 8-stage USD compensation scheme.
UPDATE "mlm_levels" SET "nom" = 'Builder', "commissionParFilleul" = 6, "commissionTotale" = 24, "bonusDescription" = '2 pagnes', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 1;
UPDATE "mlm_levels" SET "nom" = 'Sapphire', "commissionParFilleul" = 12.5, "commissionTotale" = 50, "bonusDescription" = '1er kit alimentaire', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 2;
UPDATE "mlm_levels" SET "nom" = 'Ruby', "commissionParFilleul" = 20, "commissionTotale" = 80, "bonusDescription" = '2e kit alimentaire', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 3;
UPDATE "mlm_levels" SET "nom" = 'Emerald', "commissionParFilleul" = 50, "commissionTotale" = 200, "bonusDescription" = 'Écran plat 52 pouces', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 4;
UPDATE "mlm_levels" SET "nom" = 'Diamond', "commissionParFilleul" = 250, "commissionTotale" = 1000, "bonusDescription" = 'Moto de luxe de 2 000 USD', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 5;
UPDATE "mlm_levels" SET "nom" = 'Crown Diamond', "commissionParFilleul" = 500, "commissionTotale" = 2000, "bonusDescription" = '1re voiture de 6 000 USD', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 6;
UPDATE "mlm_levels" SET "nom" = 'Ambassadeur', "commissionParFilleul" = 5000, "commissionTotale" = 20000, "bonusDescription" = '1re maison de 30 000 USD + 2e voiture de 15 000 USD', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 7;
UPDATE "mlm_levels" SET "nom" = 'Crown Ambassadeur', "commissionParFilleul" = 12500, "commissionTotale" = 50000, "bonusDescription" = '2e maison + 3e voiture', "salaireMensuel" = 0, "salaireActif" = false, "updatedAt" = CURRENT_TIMESTAMP WHERE "ordre" = 8;
